language: java
jdk: oraclejdk8
install: true
script: mvn package
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script:
  - make services_images
notifications:
  slack:
    secure: Dox9OCp33CrqLUiNt/W22izo8gD+czp5W0O7HmVFLpz2TTVF1u4qKUXWA+grNEbrG2+dIla3XtYiP8hUFA/Pwfm6U/P4wG7Bp/Q2KhLz0WilFQzQGFvvcbmwUsLoZykuWfkdeOWgGAJktBmGublb7j/1qFGcjicar14rpewW/7HHgVdDsGObZWKCQ9DziaDHsMN1kAyLnSsxP+qJYt2YKuQ+Z4itnreRxl+ut5EmRHKUuYi30KKqNyFfdd/aM7mtV0CK9My/BrlHIIc5CDijygQKuw4yF7bkeex9hC7E6WfPYxgYXbPVKxMWR0NW8Zd5rw7WV/GhWBzuIGTaiWvfR96UsHLY6xYam3m57FW9iY8pZNFb6Ya6YEpBm0WEFqaKoM81VOI+vaBY05yZv8l/wYPPos6cXKzmlZ8KD3PFibYH+VsYs64GhoaoQQAwTEltQXD4T/ZabDuyVKj8M39fN3qZD2Z761MQ9esm7CAQHx9godUMBOwK0tUN9pOiLHg6JB25pDDfyaOIWPL7illCCx7rSXmDnX0Jb38qklKiVVO+pR+mRfa1rav/xfJ85J4VJuz1mLLtrNS1To1R4YctCtNz83/yK4RTVyqQzl9XdkZTrJrI/vB21p3uroXK+fdt66aQTHSxEgnVVGiqUASesL5rL+pv8AC4pxUsZsCC+S4=
    rooms:
      secure: otNJxKUwndTrqLXVXZYCyyHKbgIMpNREco8YW4K0kqEOnSS8V+TGBhKwKjTUDdjYWJTIbuBi2g4gcFndYhS/EpL/J1IVpZps7TIC1OJOc1tGOLJpn3ABtpLAlSzpWPM3X+/jdyTUwYd4Gt+19BuThuH2xU+CMJUZomFfrunVroVFqdXnIVj0tPXMIuHbyyvpZ6pxYqAQ7qKdbQMacZl0UgC9cGx7qL7iLhUS+zfUSZbk7dSUdY5M43T6ASAQn5vGP4VTtjyICxf82cKy5Giy/m31Qsuy37q5We2rf5YyyojCvri3BXV3cVgtP5UzAh2G12k5oKQ0k9U+xX6p6/D8oK5X+88I7nD/rEqCYg+mI2FEceOXVqX1LcgICMXoZZ1zgME2+2WBc/jiniBIHvWvmGxKQOWdObPemSbD0VL+Bfa3CEKVVKLUqNHtvKiu8w/S7NOhldsdzNjEj1kJsokWVbclHighRO3Kw1Hy0RZ49GqPZlEcGYgXHxHaqNcTUTpu0b6VdsgbDEbnt9M5bG7414O+KJxHDGYVOISEOhSEKaFsPMPyPjDYKKaNzW+HPZqo+vcK/niJjB4JxhJAJwN0pWg4vvRcGAY2brYL8LHXbtPsEbjMYi+wsokzjZYeof7lR0RGnSVCs8vhqQuvQW8tmRYiu8iQmYvJ1zGINUbKFs0=
