language: java
jdk: oraclejdk8
install: true
script: mvn package
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  skip_cleanup: true
  script:
  - make services_images
notifications:
  slack:
    rooms:
      secure: 2mBgaZQ+LLW6IJpizUha6Mb7wH5qNML7rukHFZx7Pgobr24+Vs7q67YGnRsYU/Qg+ByV69kktvbPPpYiCwZ2U3smrGSe+XucsE0hzOaH8kgZ0URBzxiVrcEmhcr2eoGkijE87yLaTx3788etPf7vqeO7idDBqKM4Q/OBlN7yeAZx2XzPG3F30b5Ej40jqOFKebFkaHZ8KHTmuBwbfIGaBliHV+zitcbTX29PB0v1XRVBEJ7EMectByBeOtKgyjHkKLWVNBw6uGKINXo0vqT9OpEud1ou/3JXuNwWeIz9LkdUHwWGXvlh5/OpwGq6aKniQIKT6vmaKT8T8TZBQ5dUnwtBcxlXITrjBlkuGdNElQhfZ+CAUkisybK6HMOqbJZbZ9eJ5R6wxC1IGhDMi6F+rPl2X8ain+lM+MXJf5vmKKS7sS12UUkIv5QyI4F7EBM0U7RjFocuqjRKaLW9OAzkR5DGoRzxx/UHtftHK48+wkaFsejz/PIJS9csdrBtNwp2/6X4VYR/h0LEGwizek66tmoyYxNYBCMJEHZ+a3Td5oooLGAqAr2RIRl3/pr+hzRMtoDgb3V4XmpWs8IvsJEyULExGSivRjk/MlXk0TNdRp8xrQ9fAAXmSn/9ugnm4G4zRv1khStkPTAznkS7Wxt2GRbhtUlGfFyMb31JaUiMg4Y=
